### ISSUE TITLE
Crash when join on map

### ISSUE THREAD

**Issue by infine905** [papstuc/counterstrike2#1]
![image](https://user-images.githubusercontent.com/78636670/229346479-ca8b69e9-e85d-4962-bf7c-f13a69aa2268.png)
![image](https://user-images.githubusercontent.com/78636670/229347297-f12fd449-3ee2-4411-9a4a-9473ecdd4c20.png)

During the debag, I found this error. When I go to the map and turn on ESP, the game crashes.
Pirate version of the game (from 01.04)

**Comment by papstuc** [comment]
steam.inf file:
```
ClientVersion=2000049
ServerVersion=2000049
PatchVersion=1.38.5.8
ProductName=cs2
appID=730
ServerAppID=2347773
SourceRevision=7939620
VersionDate=Mar 22 2023
VersionTime=12:31:10
```

I have made the signatures based upon this version so the signature GET_PLAYER_FROM_CONTROLLER got invalid.

Either get my build, versions above or update the signature for your version.

Now how can you do this?
Simply xref the string "Pawn: (%d) Name: %s" in client.dll and you will find it.

<img src="https://i.imgur.com/inc7fnp.png"/>

Feel free to add me on Discord (name and tag in my bio) if you need any help!

Regards.

**Comment by x1en** [comment]
gj, thanks for your work!

**Comment by x1en** [comment]
i was having the same error but i updated signature and now i getting new error
![image](https://user-images.githubusercontent.com/75277136/229577493-b8125905-2c2e-495d-a5e0-cb5e0220ee53.png)
![image](https://user-images.githubusercontent.com/75277136/229577861-45ab9976-645b-427d-a22d-8eef6ee64f1b.png)

**Comment by papstuc** [comment]
i_renderer interface got probably outdated.
