### ISSUE TITLE
can update for $?

### ISSUE THREAD

**Issue by rohybnol** [papstuc/counterstrike2#6]
can update for $?

**Comment by r3vers** [comment]
> can update for $?

how to contact?

**Comment by rohybnol** [comment]
discord

**Comment by r3vers** [comment]
> discord

send me your discord username

**Comment by rohybnol** [comment]
you can update and ensure all features works like anti aim/silent etc?
let me know your discord

**Comment by r3vers** [comment]
> you can update and ensure all features works like anti aim/silent etc? let me know your discord
yes
dc2trill | 883688144615112775

**Comment by r3vers** [comment]
> you can update and ensure all features works like anti aim/silent etc? let me know your discord

yes
dc2trill | 883688144615112775

**Comment by r3vers** [comment]
> you can update and ensure all features works like anti aim/silent etc? let me know your discord

yes
discord: dc2trill

**Comment by rohybnol** [comment]
added you
